import axios from "axios";
import i18n from "i18next";
import LanguageDetector from "i18next-browser-languagedetector";
import { initReactI18next } from "react-i18next";

export const axiosClient = axios.create({
  baseURL: "http://127.0.0.1:3000",
});

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    debug: false,
    fallbackLng: "en",
    interpolation: {
      escapeValue: false,
    },
    resources: {
      en: {
        translation: {
          "expiration.10min": "10 minutes",
          "expiration.1hour": "1 hour",
          "expiration.1day": "1 day",
          "expiration.1week": "1 week",
          "expiration.1month": "1 month",
          "expiration.unlimited": "Unlimited",
          "paste.created": "Paste created!",
          "paste.createError": "Error creating paste",
          "pasteForm.title": "Create new paste",
          "pasteForm.placeholderTitle": "Title (optional)",
          "pasteForm.private": "Private paste",
          "pasteForm.placeholderContent": "Paste your text or code here...",
          "pasteForm.create": "Create",
          "pasteForm.needLogin": "To create a new paste, please sign in",
          "account.sectionLabel": "Account",
          "account.registeredAt": "Registered on",
          "account.noPastes": "You haven't created any pastes yet",
          "account.loading": "Loading...",
          "feed.sectionLabel": "Feed",
          "feed.noPastes": "No pastes",
          "feed.loading": "Loading...",
          "paste.loading": "Loading...",
          "paste.notFound": "Paste not found",
          "signin.title": "Sign In",
          "signin.password": "Password",
          "signin.loading": "Signing in...",
          "signin.signin": "Sign In",
          "signin.enterEmailPassword": "Enter email and password",
          "signin.success": "Signed in!",
          "signin.error": "Sign in error",
          "signup.title": "Sign Up",
          "signup.username": "Username",
          "signup.password": "Password",
          "signup.passwordPrompt": "Enter a strong password",
          "signup.weakPassword": "Weak password",
          "signup.mediumPassword": "Medium password",
          "signup.strongPassword": "Strong password",
          "signup.confirmPassword": "Repeat password",
          "signup.loading": "Signing up...",
          "signup.signup": "Sign Up",
          "signup.enterAllFields": "Enter username, email and password",
          "signup.passwordsDontMatch": "Passwords do not match",
          "signup.success": "Registration successful!",
          "signup.error": "Registration error",
          "pasteView.linkCopied": "Link copied!",
          "pasteView.rawCopied": "Raw text copied!",
          "pasteView.confirmDelete": "Are you sure you want to delete this paste?",
          "pasteView.deleted": "Paste deleted successfully!",
          "pasteView.deleteErrorLog": "Error deleting paste:",
          "pasteView.deleteError": "Failed to delete paste. Try again later.",
          "pasteView.copyLink": "Copy link",
          "pasteView.copyRaw": "Copy raw",
          "pasteView.link": "Link",
          "pasteView.raw": "Raw",
          "pasteView.deletePaste": "Delete paste",
          "pasteView.noTitle": "No title",
          "pasteView.author": "Author",
          "pasteView.privacy": "Privacy",
          "pasteView.private": "Private",
          "pasteView.public": "Public",
          "pasteView.created": "Created",
          "pasteView.expires": "Expires",
          "pasteView.expiresNever": "Never",
          "pasteTable.title": "Title",
          "pasteTable.createdAt": "Created at",
          "pasteTable.syntax": "Syntax",
          "pasteTable.noTitle": "No title",
          "pasteTable.author": "Author",
          "header.newPaste": "Paste",
          "header.feed": "Feed",
          "header.signIn": "Sign In",
          "header.signUp": "Sign Up",
          "header.logout": "Log out",
          "feedPreview.latestPastes": "Latest pastes",
          "feedPreview.noPastes": "No pastes",
          "feedPreview.loading": "Loading...",
          "feedPreview.noTitle": "No title",
          "feedPreview.author": "Author",
          "feedPreview.justNow": "Just now",
          "feedPreview.oneHour": "hour",
          "feedPreview.fewHours": "hours",
          "feedPreview.manyHours": "hours",
          "feedPreview.oneMinute": "minute",
          "feedPreview.fewMinutes": "minutes",
          "feedPreview.manyMinutes": "minutes",
          "feedPreview.oneSecond": "second",
          "feedPreview.fewSeconds": "seconds",
          "feedPreview.manySeconds": "seconds",
          "feedPreview.ago": "ago",
        },
      },
      ru: {
        translation: {
          "expiration.10min": "10 минут",
          "expiration.1hour": "1 час",
          "expiration.1day": "1 день",
          "expiration.1week": "1 неделя",
          "expiration.1month": "1 месяц",
          "expiration.unlimited": "Без ограничения",
          "paste.created": "Паста создана!",
          "paste.createError": "Ошибка при создании пасты",
          "pasteForm.title": "Создать новую пасту",
          "pasteForm.placeholderTitle": "Заголовок (необязательно)",
          "pasteForm.private": "Приватная паста",
          "pasteForm.placeholderContent": "Вставьте ваш текст или код сюда...",
          "pasteForm.create": "Создать",
          "pasteForm.needLogin": "Чтобы создать новую пасту, войдите в аккаунт",
          "account.sectionLabel": "Аккаунт",
          "account.registeredAt": "Дата регистрации",
          "account.noPastes": "Вы еще не создавали паст",
          "account.loading": "Загрузка...",
          "feed.sectionLabel": "Лента",
          "feed.noPastes": "Нет паст",
          "feed.loading": "Загрузка...",
          "paste.loading": "Загрузка...",
          "paste.notFound": "Паста не найдена",
          "signin.title": "Вход",
          "signin.password": "Пароль",
          "signin.loading": "Вход...",
          "signin.signin": "Войти",
          "signin.enterEmailPassword": "Введите email и пароль",
          "signin.success": "Вход выполнен!",
          "signin.error": "Ошибка входа",
          "signup.title": "Регистрация",
          "signup.username": "Имя пользователя",
          "signup.password": "Пароль",
          "signup.passwordPrompt": "Введите надежный пароль",
          "signup.weakPassword": "Слабый пароль",
          "signup.mediumPassword": "Средний пароль",
          "signup.strongPassword": "Надежный пароль",
          "signup.confirmPassword": "Повторите пароль",
          "signup.loading": "Регистрация...",
          "signup.signup": "Зарегистрироваться",
          "signup.enterAllFields": "Введите имя пользователя, email и пароль",
          "signup.passwordsDontMatch": "Пароли не совпадают",
          "signup.success": "Регистрация успешна!",
          "signup.error": "Ошибка регистрации",
          "pasteView.linkCopied": "Ссылка скопирована!",
          "pasteView.rawCopied": "Raw-текст скопирован!",
          "pasteView.confirmDelete": "Вы уверены, что хотите удалить эту пасту?",
          "pasteView.deleted": "Паста успешно удалена!",
          "pasteView.deleteErrorLog": "Ошибка при удалении пасты:",
          "pasteView.deleteError": "Не удалось удалить пасту. Попробуйте позже.",
          "pasteView.copyLink": "Скопировать ссылку",
          "pasteView.copyRaw": "Скопировать Raw-текст",
          "pasteView.link": "Ссылка",
          "pasteView.raw": "Raw",
          "pasteView.deletePaste": "Удалить пасту",
          "pasteView.noTitle": "Без заголовка",
          "pasteView.author": "Автор",
          "pasteView.privacy": "Приватность",
          "pasteView.private": "Приватная",
          "pasteView.public": "Публичная",
          "pasteView.created": "Создана",
          "pasteView.expires": "Истекает",
          "pasteView.expiresNever": "Никогда",
          "pasteTable.title": "Название",
          "pasteTable.createdAt": "Дата создания",
          "pasteTable.syntax": "Синтаксис",
          "pasteTable.noTitle": "Без названия",
          "pasteTable.author": "Автор",
          "header.newPaste": "Паста",
          "header.feed": "Лента",
          "header.signIn": "Войти",
          "header.signUp": "Зарегистрироваться",
          "header.logout": "Выйти",
          "feedPreview.latestPastes": "Последние пасты",
          "feedPreview.noPastes": "Нет паст",
          "feedPreview.loading": "Загрузка...",
          "feedPreview.noTitle": "Без названия",
          "feedPreview.author": "Автор",
          "feedPreview.justNow": "Только что",
          "feedPreview.oneHour": "час",
          "feedPreview.fewHours": "часа",
          "feedPreview.manyHours": "часов",
          "feedPreview.oneMinute": "минута",
          "feedPreview.fewMinutes": "минуты",
          "feedPreview.manyMinutes": "минут",
          "feedPreview.oneSecond": "секунда",
          "feedPreview.fewSeconds": "секунды",
          "feedPreview.manySeconds": "секунд",
          "feedPreview.ago": "назад",
        },
      },
    },
  });

export default i18n;
